...\" $Header: /usr/src/docbook-to-man/cmd/RCS/docbook-to-man.sh,v 1.3 1996/06/17 03:36:49 fld Exp $
...\"
...\"	transcript compatibility for postscript use.
...\"
...\"	synopsis:  .P! <file.ps>
...\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "PCL3OPTS" "1" "" "pcl3 3.2"
.SH "NAME"
pcl3opts \(em determine options for the ghostscript driver \fBpcl3\fP from a PCL-3+ file
.SH "SYNOPSIS"
.PP
\fBpcl3opts\fP [\fB-o \fIoutput_file\fP\fP]  [\fIinput_file\fP \&...] 
.SH "DESCRIPTION"
.PP
The command \fBpcl3opts\fP
is intended to help in determining which options one should use when
calling ghostscript using \fBpcl3\fP for driving a PCL-3+ printer\&.
It analyzes one or more PCL \fIinput_files\fP
and issues on the \fIoutput_file\fP
its best guess as to which options one should specify in order to produce
files using a similar configuration\&.
The default \fIoutput_file\fP is standard output\&.
If no \fIinput_files\fP are specified,
the command reads from standard input\&.
.PP
This command is mostly of interest if you have access to PCL files generated by
software provided by the printer\&'s manufacturer,
for example if you have a manufacturer-supplied
Microsoft Windows driver for your printer\&.
In that case you can generate a few files under Windows using different
settings and let \fBpcl3opts\fP examine them\&.
.SH "LIMITATIONS"
.PP
Note that \fBpcl3opts\fP
cannot guarantee that the collection of options it proposes leads to a file
which is understood by the printer\&.
It can merely provide a best guess\&.
.PP
In addition, some settings require interpretation of the page contents
in order to properly translate them into options for \fBpcl3\fP
and some cannot reliably be derived from a PCL file at all\&.
Finding good values for these parameters is beyond
\fBpcl3opts\fP\&'s capabilities\&.
This includes \fBLeadingEdge\fP, \fBSendBlackLast\fP,
\fBTumble\fP and the distinction between the colour models
\fBCMY+K\fP and \fBCMYK\fP\&.
.SH "SEE ALSO"
.PP
\fBgs-pcl3\fP\fB(1)\fP
.SH "AUTHOR"
.PP
Copyright © 2000, 2001 by Martin Lottermoser,
Greifswaldstraﬂe 28, 38124 Braunschweig, Germany\&.
E-mail: Martin\&.Lottermoser@t-online\&.de\&.
.PP
Version of this reference page: $Revision: 1\&.10 $
($Date: 2001/02/10 17:01:06 $)\&.
...\" created by instant / docbook-to-man, Sun 19 Aug 2001, 12:15
