#!/usr/bin/env python2.1

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This software is provided AS-IS with no warranty, either express or
# implied.
# 
# This software is distributed under license and may not be copied,
# modified or distributed except as expressly authorized under the terms
# of the license contained in the file LICENSE in this distribution.
# 
# For more information about licensing, please refer to
# http://www.ghostscript.com/licensing/. For information on
# commercial licensing, go to http://www.artifex.com/licensing/ or
# contact Artifex Software, Inc., 101 Lucas Valley Road #110,
# San Rafael, CA  94903, U.S.A., +1(415)492-9861.

# $RCSfile$ $Revision$

#
# dump_testdb [<dbfile>]
#
# dumps (prints out) the contents of the testdatadb

import sys, anydbm, gsconf

if len(sys.argv) == 2:
    print "opening ", sys.argv[1]
    db = anydbm.open(sys.argv[1])
else:
    db = anydbm.open(gsconf.testdatadb)

for k in db.keys():
    print db[k], k

