#!/usr/bin/env python2.1
# -*- Mode: python -*-

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This software is provided AS-IS with no warranty, either express or
# implied.
# 
# This software is distributed under license and may not be copied,
# modified or distributed except as expressly authorized under the terms
# of the license contained in the file LICENSE in this distribution.
# 
# For more information about licensing, please refer to
# http://www.ghostscript.com/licensing/. For information on
# commercial licensing, go to http://www.artifex.com/licensing/ or
# contact Artifex Software, Inc., 101 Lucas Valley Road #110,
# San Rafael, CA  94903, U.S.A., +1(415)492-9861.

# $Id$

#
# run_regression
#
# runs ghostscript regression tests

import sys
import anydbm
import gstestutils, gsconf
import check_all
import gscheck_all

track = 0
if len(sys.argv) > 1:
    if sys.argv[1] == "--track":
        track = 1

        db = anydbm.open(gsconf.get_dailydb_name(), "n")
        db.close()
        
suite = gstestutils.GSTestSuite()

# Add tests based on running Ghostscript.
gscheck_all.addTests(suite, gsroot=gsconf.gsroot, track=track)

# Add tests not based on actually running Ghostscript.
check_all.addTests(suite, gsroot=gsconf.gsroot)

# run all the tests
runner = gstestutils.GSTestRunner(verbosity=2)
result = runner.run(suite)

