.TH PFBTOPFA 1 "18 Sept 2024" 10.04.0 Ghostscript \" -*- nroff -*-
.SH NAME
pfbtopfa \- Convert Postscript .pfb fonts to .pfa format using ghostscript
.SH SYNOPSIS
\fBpfbtopfa\fR \fIinput.pfb\fR \fI[output.pfa]\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a .pfb file into a .pfa file.
.SH SEE ALSO
\fBgs\fR(1)
.SH VERSION
This document was last revised for Ghostscript version 10.04.0.
.SH AUTHOR
Artifex Software, Inc. are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
