== GhostPDL ==

This is an implemenation of several page description languages on
top of the Ghostscript graphics library.

Ghostscript PCL5e, PCL5c and PXL documentation is in doc/ghostpcl.*
License is in LICENSE and COPYING. For information on support and 
commercial distribution please contact http://artifex.com/

=== BUILD INSTRUCTIONS ===

We encourage you to read the documentation and licence information but
the software can be quickly built and installed on many unix systems
by executing these commands.  Do not type the number or the period
before each command.

If you are using GNU Make, a complete build can be generated by just
typing:

make

in the top level source directory. This will create three different 
builds. In main/obj/pcl6 a build of GhostPCL with support for PCL5e, 
PCL5c, and PXL. In language_switch/obj/pspcl6 a build of GhostPCL with 
additional support for PostScript and PDF. In xps/obj/gxps a build
with support for XPS.

NB We have seen some problems with the optimized PCL build on x86_64
with gcc 4.x. If you have trouble getting correct output, try building 
with -O instead of -O2.

===

The same executables can be built with Microsoft Visual C by running
the appropriate *_mvsc.mak file through nmake. For example:

cd xps
nmake -f xps_msvc.mak

or

cd main
nmake -f pcl6_msvc.mak

The makefiles default to supporting MSVC 8 (2005) To use another 
version, append it to the nmake command line, for example:

cd main
nmake -f pcl6_msvc.mak MSVC_VERSION=6

===

To build the just xps interpreter with GNU make and gcc, type:

make xps

The executable will be xps/obj/gxps.

To build just the PCL/PXL interpreter

1. make fonts  # installs truetype fonts.
2. make        # use make debug for a diagnostic system.
3. make test   # run a pcl and pxl job using the default display device.
4. make install

1. and 4. may require administrator privileges.

To build a shared language build with PCL/PXL and PostScript/PDF

make ls_product

The executable with be in language_switch/obj/pspcl6

===

Note for cygwin users

make CYGWIN=TRUE
make install

The CYGWIN variable will not include devices that depend on threads or
X11, neither are supported by the default cygwin system.

To build with a different font scaler use:

make PL_SCALER=afs ... # build using the Artifex Font scaler also the default.
make PL_SCALER=ufst ...# build with the AGFA Font Scaler.

We recommend doing a clean make prior to the changing the font scaler.

The default location for the fonts is /windows/fonts, but the current 
working directory is also searched. If the fonts are placed in another 
location the environment variable PCLFONTSOURCE must be set accordingly.  
See the documentation for more details.
