.\"- -*- nroff -*- - - - - - - - - - - - - - - - - - - - - - - - - - - - -
.\"
.\"This file describes version 5.03 of Aladdin pdf2ps.
.\"
.\"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
.de TQ
.br
.ns
.TP \\$1
..
.TH pdf2ps 1 "10 November 1997"
.SH NAME 
pdf2ps \- Aladdin Ghostscript PDF to PostScript translator
.SH SYNOPSIS
.B pdf2ps input.pdf output.ps
.br
.SH DESCRIPTION
pdf2ps converts the Adobe Portable Document Format (PDF) file input.pdf to
Level 2 PostScript in output.ps.  pdf2ps uses gs(1).  See
/usr/local/lib/ghostscript/M.N/doc/use.txt for more details,
where M.N is the Ghostscript version number.
