.\" Id: pdf2ps.1 
.TH PDF2PS 1 "23 June 1998" 5.24 "Ghostscript Tools" \" -*- nroff -*-
.SH NAME
pdf2ps \- Ghostscript PDF to PostScript translator
.SH SYNOPSIS
\fBpdf2ps\fR [ \fIoptions\fR ] \fIinput.pdf output.ps\fR
.SH DESCRIPTION
\fBpdf2ps\fR uses \fBgs\fR(1) to convert the \fBAdobe Portable Document
Format\fR (PDF) file "input.pdf" to Level 2 \fBPostScript\fR(tm) in
"output.ps".
.SH FILES
Run "\fBgs -h\fR" to find the location of Ghostscript documentation on your
system, from which you can get more details.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com>
