.\" $Id$
.TH PS2PDFWR 1 "31 March 2001" 6.63 Ghostscript \" -*- nroff -*-
.SH NAME
ps2pdfwr \- Convert PostScript to PDF without specifying CompatibilityLevel, using ghostscript
.SH SYNOPSIS
\fBps2pdfwr\fR  [options...] (input.[e]ps|-) [output.pdf|-]
.SH DESCRIPTION
This script invokes
.BR gs (1)
with following arguments

.ce
.B -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite

as well as the
.B -dOutputFile
argument, all preceded and followed by any command-line arguemnts.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 6.63.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com> is the principal author of Ghostscript.
Russell J. Lang <rjl@aladdin.com> is the author of most of the MS Windows
code in Ghostscript.
This manpage by George Ferguson.
