
.TH PS2PDF 1 "16 August 1998" 5.30 "Ghostscript Tools" \" -*- nroff -*-
.SH NAME
ps2pdf \- Ghostscript PostScript to PDF translator
.SH SYNOPSIS
\fBps2pdf\fR [ \fIoptions\fR ] \fIinput.ps output.pdf\fR
.SH DESCRIPTION
\fBps2pdf\fR uses \fBgs\fR(1) to convert the \fBPostScript\fR(tm) file
"input.ps" to the Adobe \fBPortable Document Format\fR (PDF) in
"output.pdf."
.PP
With one exception, \fBps2pdf\fR is a pretty good workalike for Adobe
\fBAcrobat\fR(tm) \fBDistiller\fR(tm) 3.0.  It implements
"setdistillerparams" and nearly all of Distiller's compression and image
downsampling options, except for LZW compression (thanks to Unisys).  By
default it produces PDF 1.2 output compatible with Acrobat 3.x, compressed
with "deflate" (also known as "zip" or "gzip") compression;
to produce PDF 1.1 output compatible with Acrobat 2.x, use the
\fB-dCompatibilityLevel=1.1\fR option.
.PP
The one current great shortcoming of \fBps2pdf\fR is that except for the
fourteen built-in PDF fonts, it converts all fonts in the PostScript file
to bitmap fonts in the PDF file, and scrambles the character codes so that
the output is not searchable.  (Normally it produces 720dpi bitmaps, but
you can change this using Ghostscript's \fB\-r\fR option.)  We intend to
mostly fix this some time in 1998.
.SH FILES
Run "\fBgs -h\fR" to find the location of Ghostscript documentation on your
system, from which you can get more details.
.SH VERSION
This document was last revised for Ghostscript version 5.30.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com>
