.\" $Id$
.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de>
.TH PS2PS 1 "21. Februar 2000" 6.01 "Ghostscript Werkzeuge" \" -*- nroff -*-
.SH NAME
eps2eps \- Ghostscript Encapsulated PostScript "Distiller"
.SH SYNOPSIS
\fBeps2eps\fR [ \fIOptionen\fR ] \fIEingabe.eps Ausgabe.eps\fR
.SH Beschreibung
\fBeps2eps\fR benutzt \fIgs\fR(1) um die Encapsulated-\fBPostScript\fR(tm)-Datei (EPS-Datei) "Eingabe.eps" in einfacheres und (meist) schnelleres Encapsulated PostScript zu konvertieren und in die Datei "Ausgabe.eps" zu schreiben. Normalerweise darf die Ausgabe PostScript-Level-2-Konstrukte benutzen, aber die \fB\-dLanguageLevel=1\fR-Option erzwingt die Ausgabe von Level 1.
.PP
Benutzen Sie \fBeps2eps\fR nur für Encapsulated-PostScript-(EPS-)Dateien; für normalen PostScript-(PS-)Dateien sollten Sie \fBps2ps\fR benutzen.
.SH DATEIEN
Starten Sie "\fBgs -h\fR" um den Ort der Ghostscript-Documentation auf Ihrem System herauszubekommen, wo sie weitere Informationen erhalten.
.SH VERSION
Dieses Dokument wurde zuletzt für Ghostscript Version 6.01 durchgesehen.
.SH AUTOR
L. Peter Deutsch <ghost@aladdin.com>
