.\" $Id$
.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de>
.TH GSND 1 "3. Februar 2000" 6.0 Ghostscript \" -*- nroff -*-
.SH NAME
gsnd \- statet Ghostscript (PostScript- und PDF-Engine) ohne Display
.SH SYNOPSIS
\fBgsnd\fR [ \fIOptionen\fR ] [ \fIDateinen\fR ] ...
.SH BESCHREIBUNG
Das Skript ruft einfach
.BR gs (1)
mit der Option
.B -NODISPLAY
auf, gefolgt von allen anderen Argumenten der Kommandozeile.
.SH SIEHE AUCH
gs(1)
.SH VERSION
Dieses Dokument wurde zuletzt für Ghostscript Version 6.0 durchgesehen.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com> ist der Hauptautor von Ghostscript.
Russell J. Lang <rjl@aladdin.com> ist der Autor des Hauptteils des MS-Windows Quelltexts in Ghostscript.
Diese Manpage ist von George Ferguson.
