.\" $Id$
.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de>
.TH PRINTAFM 1 "3. Februar 2000" 6.0 Ghostscript \" -*- nroff -*-
.SH NAME
printafm \- Gibt die Metrik einer Postscript-Schrift im AFM-Format mittels ghostscript aus
.SH SYNTAX
\fBprintafm\fR \fISchriftname\fR
.SH BESCHREIBUNG
Dieses Skript ruft
.BR gs (1)
auf, um die Metrik einer Schrift im AFM-Format zur Standardausgabe (stdout) zu schreiben.
.SH SIEHE AUCH
gs(1)
.SH VERSION
Das Dokument wurde zuletzt für Ghostscript Version 6.0 durchgesehen.
.SH AUTOR
L. Peter Deutsch <ghost@aladdin.com> ist der Hauptautor von Ghostscript.
Russell J. Lang <rjl@aladdin.com> ist der Autor des Hauptteils des MS-Windows Quelltexts in Ghostscript.
Diese Manpage ist von George Ferguson.

