#!/usr/bin/env python2.1

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This file is part of AFPL Ghostscript.
# 
# AFPL Ghostscript is distributed with NO WARRANTY OF ANY KIND.  No author or
# distributor accepts any responsibility for the consequences of using it, or
# for whether it serves any particular purpose or works at all, unless he or
# she says so in writing.  Refer to the Aladdin Free Public License (the
# "License") for full details.
# 
# Every copy of AFPL Ghostscript must include a copy of the License, normally
# in a plain ASCII text file named PUBLIC.  The License grants you the right
# to copy, modify and redistribute AFPL Ghostscript, but only under certain
# conditions described in the License.  Among other things, the License
# requires that the copyright notice and this notice be preserved on all
# copies.

# $Id$

#
# make_two_versions <filename> [<device> [<res>]]
#
# this script creates two versions of the file specified
# one from baseline, and one from head
# these are appropriate for a visual diff

import gstest
import gsconf
import os, sys
import string

file = sys.argv[1]
if len(sys.argv) > 2:
	device = sys.argv[2]
else:
	device = 'ppmraw'
if len(sys.argv) > 3:
	res = int(sys.argv[3])
else:
	res = 72

ofile = "%s.%s.baseline.pnm" % (file, device)

gs = gstest.Ghostscript()
gs.command = gsconf.baselinegs
gs.infile = gsconf.comparefiledir + file
gs.outfile = ofile
gs.device = device
gs.dpi = res
gs.band = 0
gs.gsoptions = gsconf.baselineoptions

gs.process()

ofile = "%s.%s.compare.pnm" % (file, device)

gs = gstest.Ghostscript()
gs.command = gsconf.comparegs
gs.infile = gsconf.comparefiledir + file
gs.outfile = ofile
gs.device = device
gs.dpi = res
gs.band = 0
gs.gsoptions = gsconf.compareoptions

gs.process()
