#!/usr/bin/env python2.1

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This file is part of AFPL Ghostscript.
# 
# AFPL Ghostscript is distributed with NO WARRANTY OF ANY KIND.  No author or
# distributor accepts any responsibility for the consequences of using it, or
# for whether it serves any particular purpose or works at all, unless he or
# she says so in writing.  Refer to the Aladdin Free Public License (the
# "License") for full details.
# 
# Every copy of AFPL Ghostscript must include a copy of the License, normally
# in a plain ASCII text file named PUBLIC.  The License grants you the right
# to copy, modify and redistribute AFPL Ghostscript, but only under certain
# conditions described in the License.  Among other things, the License
# requires that the copyright notice and this notice be preserved on all
# copies.

# $Id$

#
# run_regression
#
# runs ghostscript regression tests

import unittest, os
import gsconf, gstest

# get a list of test files
comparefiles = os.listdir(gsconf.comparefiledir)

suite = unittest.TestSuite()

# add compare tests
def add_compare_test(suite, f, device, dpi, band):
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs,
                                               file=gsconf.comparefiledir + f,
                                          device=device, dpi=dpi, band=band))

for f in comparefiles:
    if f[-3:] == '.ps' or f[-4:] == '.pdf' or f[-4:] == '.eps':
        add_compare_test(suite, f, 'pbmraw', 72, 0)
        add_compare_test(suite, f, 'pbmraw', 72, 1)
        add_compare_test(suite, f, 'pbmraw', 300, 0)
        add_compare_test(suite, f, 'pbmraw', 300, 1)
        #add_compare_test(suite, f, 'pbmraw', 600, 0)
        #add_compare_test(suite, f, 'pbmraw', 600, 1)

        add_compare_test(suite, f, 'pgmraw', 72, 0)
        add_compare_test(suite, f, 'pgmraw', 72, 1)
        add_compare_test(suite, f, 'pgmraw', 300, 0)
        add_compare_test(suite, f, 'pgmraw', 300, 1)
        #add_compare_test(suite, f, 'pgmraw', 600, 0)
        #add_compare_test(suite, f, 'pgmraw', 600, 1)

        add_compare_test(suite, f, 'ppmraw', 72, 0)
        add_compare_test(suite, f, 'ppmraw', 72, 1)
        add_compare_test(suite, f, 'ppmraw', 300, 0)
        add_compare_test(suite, f, 'ppmraw', 300, 1)
        #add_compare_test(suite, f, 'ppmraw', 600, 0)
        #add_compare_test(suite, f, 'ppmraw', 600, 1)

        add_compare_test(suite, f, 'pkmraw', 72, 0)
        add_compare_test(suite, f, 'pkmraw', 72, 1)
        add_compare_test(suite, f, 'pkmraw', 300, 0)
        add_compare_test(suite, f, 'pkmraw', 300, 1)
        #add_compare_test(suite, f, 'pkmraw', 600, 0)
        #add_compare_test(suite, f, 'pkmraw', 600, 1)

# run all the tests
runner = gstest.GSTestRunner(verbosity=2)
result = runner.run(suite)

