#!/usr/bin/env python2.1

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This file is part of AFPL Ghostscript.
# 
# AFPL Ghostscript is distributed with NO WARRANTY OF ANY KIND.  No author or
# distributor accepts any responsibility for the consequences of using it, or
# for whether it serves any particular purpose or works at all, unless he or
# she says so in writing.  Refer to the Aladdin Free Public License (the
# "License") for full details.
# 
# Every copy of AFPL Ghostscript must include a copy of the License, normally
# in a plain ASCII text file named PUBLIC.  The License grants you the right
# to copy, modify and redistribute AFPL Ghostscript, but only under certain
# conditions described in the License.  Among other things, the License
# requires that the copyright notice and this notice be preserved on all
# copies.

# $Id$

#
# run_regression
#
# runs ghostscript regression tests

import unittest, os
import gsconf, gstest

# get a list of test files
crashfiles = os.listdir(gsconf.crashfiledir)
comparefiles = os.listdir(gsconf.comparefiledir)

suite = unittest.TestSuite()

# add compare tests
for f in comparefiles:
    if f[-3:] == '.ps' or f[-4:] == '.pdf' or f[-4:] == '.eps':
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pbmraw', dpi=72, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pbmraw', dpi=72, band=1))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pbmraw', dpi=300, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pbmraw', dpi=300, band=1))
#    suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pbmraw', dpi=600, band=0))
#    suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pbmraw', dpi=600, band=1))

        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pgmraw', dpi=72, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pgmraw', dpi=72, band=1))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pgmraw', dpi=300, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pgmraw', dpi=300, band=1))
#    suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pgmraw', dpi=600, band=0))
#    suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pgmraw', dpi=600, band=1))

        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='ppmraw', dpi=72, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='ppmraw', dpi=72, band=1))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='ppmraw', dpi=300, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='ppmraw', dpi=300, band=1))
#    suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='ppmraw', dpi=600, band=0))
#    suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='ppmraw', dpi=600, band=1))

        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pkmraw', dpi=72, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pkmraw', dpi=72, band=1))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pkmraw', dpi=300, band=0))
        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pkmraw', dpi=300, band=1))
#        suite.addTest(gstest.GSCompareTestCase(gs=gsconf.comparegs, file=gsconf.comparefiledir + f, device='pkmraw', dpi=600, band=0))



# run all the tests
runner = gstest.GSTestRunner(verbosity=2)
result = runner.run(suite)

