#!/usr/bin/env python2.1

#    Copyright (C) 2001 Artifex Software Inc.
# 
# This file is part of AFPL Ghostscript.
# 
# AFPL Ghostscript is distributed with NO WARRANTY OF ANY KIND.  No author or
# distributor accepts any responsibility for the consequences of using it, or
# for whether it serves any particular purpose or works at all, unless he or
# she says so in writing.  Refer to the Aladdin Free Public License (the
# "License") for full details.
# 
# Every copy of AFPL Ghostscript must include a copy of the License, normally
# in a plain ASCII text file named PUBLIC.  The License grants you the right
# to copy, modify and redistribute AFPL Ghostscript, but only under certain
# conditions described in the License.  Among other things, the License
# requires that the copyright notice and this notice be preserved on all
# copies.

# $Id$

import os
import re
import time
import string

# configuration variables

MAIL_SERVER = 'localhost'
REPORT_EMAIL = 'gs-regression@ghostscript.com'
MAIL_FROM = 'regression@casper.ghostscript.com'
HEAD_DIR = '/path/to/cvs'
REGRESSION_SCRIPT = 'run_regression 2>&1'


def sendmail(frm, to, subject, text):
	import smtplib

	msg = 'From: %s\r\nTo: %s\r\nSubject: %s\r\n\r\n%s' % (frm, to, subject, text)

	server = smtplib.SMTP(MAIL_SERVER)
	server.sendmail(frm, to, msg)
	server.quit()

def update_ghostscript():
	cwd = os.getcwd()
	os.chdir(HEAD_DIR)
	
	if os.system("cvs update -Pd > /dev/null 2> /dev/null") != 0: return -1
	if os.system("make clean > /dev/null 2> /dev/null") != 0: return -1
	if os.system("make > /dev/null 2> /dev/null") != 0: return -1
	if os.system("make install > /dev/null 2> /dev/null") != 0: return -1

	return 0


if update_ghostscript() != 0:
	sendmail(MAIL_FROM, REPORT_EMAIL, 'error running regression', 'There was an error updating and building ghostscript from CVS.  Please investigate.')
	exit(0)

p = os.popen(REGRESSION_SCRIPT)
if p == None:
	sendmail(MAIL_FROM, REPORT_EMAIL, 'error running regression', 'There was an error updating and building ghostscript from CVS.  Please investigate.')
	exit(0)

pattern = 'ok$'
msg = ''
for line in p.readlines():
	if re.search(pattern, line):
		continue
	msg = msg + line
	
p.close()

sendmail(MAIL_FROM, REPORT_EMAIL, 'gs regression report - %s' % (time.strftime('%Y-%m-%d'),), msg)
