#! /bin/sh

# psf2dsc: generates an index of a PDF file.
#
# Yves Arrouye <arrouye@debian.org>, 1996.

me=`basename $0`

usage() {
    >&2 echo usage: $me "pdffile [ dscfile ]"
    exit 1
}

if [ $# -gt 2 ]
then
    usage
fi

pdffile=$1
dscfile=$2
: ${dscfile:=`echo $pdffile | sed 's,\.[^/.]*,,'`.dsc}

exec gs -q -dNODISPLAY \
    -sPDFname="$pdffile" -sDSCname="$dscfile" pdf2dsc.ps -c quit
