#!/bin/sh
# $Id$
# Make an AFM file from PFB / PFA and (optionally) PFM files.  Usage:
#	pf2afm fontfilename
# Output goes to fontfilename.afm, which must not already exist.
# See pf2afm.ps for more details.

exec gs -q -dNODISPLAY -- pf2afm.ps "$@"
