/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_gsjava_GSAPI */

#ifndef _Included_com_artifex_gsjava_GSAPI
#define _Included_com_artifex_gsjava_GSAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_gsjava_GSAPI_GS_NULL
#define com_artifex_gsjava_GSAPI_GS_NULL 0i64
#undef com_artifex_gsjava_GSAPI_GS_ERROR_OK
#define com_artifex_gsjava_GSAPI_GS_ERROR_OK 0L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNKNOWNERROR
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNKNOWNERROR -1L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_DICTFULL
#define com_artifex_gsjava_GSAPI_GS_ERROR_DICTFULL -2L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_DICTSTACKOVERFLOW
#define com_artifex_gsjava_GSAPI_GS_ERROR_DICTSTACKOVERFLOW -3L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_DICTSTACKUNDERFLOW
#define com_artifex_gsjava_GSAPI_GS_ERROR_DICTSTACKUNDERFLOW -4L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_EXECSTACKOVERFLOW
#define com_artifex_gsjava_GSAPI_GS_ERROR_EXECSTACKOVERFLOW -5L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INTERRUPT
#define com_artifex_gsjava_GSAPI_GS_ERROR_INTERRUPT -6L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDACCESS
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDACCESS -7L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDEXIT
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDEXIT -8L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDFILEACCESS
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDFILEACCESS -9L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDFONT
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDFONT -10L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDRESTORE
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDRESTORE -11L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_IOERROR
#define com_artifex_gsjava_GSAPI_GS_ERROR_IOERROR -12L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_LIMITCHECK
#define com_artifex_gsjava_GSAPI_GS_ERROR_LIMITCHECK -13L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_NOCURRENTPOINT
#define com_artifex_gsjava_GSAPI_GS_ERROR_NOCURRENTPOINT -14L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_RANGECHECK
#define com_artifex_gsjava_GSAPI_GS_ERROR_RANGECHECK -15L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_STACKOVERFLOW
#define com_artifex_gsjava_GSAPI_GS_ERROR_STACKOVERFLOW -16L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_STACKUNDERFLOW
#define com_artifex_gsjava_GSAPI_GS_ERROR_STACKUNDERFLOW -17L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_SYNTAXERROR
#define com_artifex_gsjava_GSAPI_GS_ERROR_SYNTAXERROR -18L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_TIMEOUT
#define com_artifex_gsjava_GSAPI_GS_ERROR_TIMEOUT -19L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_TYPECHECK
#define com_artifex_gsjava_GSAPI_GS_ERROR_TYPECHECK -20L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINED
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINED -21L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINEDFILENAME
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINEDFILENAME -22L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINEDRESULT
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINEDRESULT -23L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNMATCHEDMARK
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNMATCHEDMARK -24L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_VMERROR
#define com_artifex_gsjava_GSAPI_GS_ERROR_VMERROR -25L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_CONFIGURATION_ERROR
#define com_artifex_gsjava_GSAPI_GS_ERROR_CONFIGURATION_ERROR -26L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINEDRESOURCE
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNDEFINEDRESOURCE -27L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_UNREGISTERED
#define com_artifex_gsjava_GSAPI_GS_ERROR_UNREGISTERED -28L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDCONTEXT
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALIDCONTEXT -29L
#undef com_artifex_gsjava_GSAPI_GS_ERROR_INVALID
#define com_artifex_gsjava_GSAPI_GS_ERROR_INVALID -30L
/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_revision
 * Signature: (Lcom/artifex/gsjava/GSAPI$Revision;I)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1revision
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_new_instance
 * Signature: (Lcom/artifex/gsjava/LongReference;J)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1new_1instance
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_delete_instance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1delete_1instance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_stdio_with_handle
 * Signature: (JLcom/artifex/gsjava/callbacks/IStdInFunction;Lcom/artifex/gsjava/callbacks/IStdOutFunction;Lcom/artifex/gsjava/callbacks/IStdErrFunction;J)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1stdio_1with_1handle
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jlong);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_stdio
 * Signature: (JLcom/artifex/gsjava/callbacks/IStdInFunction;Lcom/artifex/gsjava/callbacks/IStdOutFunction;Lcom/artifex/gsjava/callbacks/IStdErrFunction;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1stdio
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_poll_with_handle
 * Signature: (JLcom/artifex/gsjava/callbacks/IPollFunction;J)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1poll_1with_1handle
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_poll
 * Signature: (JLcom/artifex/gsjava/callbacks/IPollFunction;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1poll
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_display_callback
 * Signature: (JLcom/artifex/gsjava/callbacks/DisplayCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1display_1callback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_register_callout
 * Signature: (JLcom/artifex/gsjava/callbacks/ICalloutFunction;J)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1register_1callout
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_deregister_callout
 * Signature: (JLcom/artifex/gsjava/callbacks/ICalloutFunction;J)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1deregister_1callout
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_arg_encoding
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1arg_1encoding
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_set_default_device_list
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1set_1default_1device_1list
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_get_default_device_list
 * Signature: (JLcom/artifex/gsjava/ByteArrayReference;Lcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1get_1default_1device_1list
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_init_with_args
 * Signature: (JILcom/artifex/gsjava/ByteArrayReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1init_1with_1args
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_run_string_begin
 * Signature: (JILcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1run_1string_1begin
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_run_string_continue
 * Signature: (J[BIILcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1run_1string_1continue
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_run_string_end
 * Signature: (JILcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1run_1string_1end
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_run_string_with_length
 * Signature: (J[BIILcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1run_1string_1with_1length
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_run_string
 * Signature: (J[BILcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1run_1string
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_run_file
 * Signature: (J[BILcom/artifex/gsjava/IntReference;)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1run_1file
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     com_artifex_gsjava_GSAPI
 * Method:    gsapi_exit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_GSAPI_gsapi_1exit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
