/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artifex_gsjava_util_NativePointer */

#include "settings.h"

#ifndef _Included_com_artifex_gsjava_util_NativePointer
#define _Included_com_artifex_gsjava_util_NativePointer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artifex_gsjava_util_NativePointer_NULL
#define com_artifex_gsjava_util_NativePointer_NULL 0i64
#undef com_artifex_gsjava_util_NativePointer_BYTE_SIZE
#define com_artifex_gsjava_util_NativePointer_BYTE_SIZE 1i64
#undef com_artifex_gsjava_util_NativePointer_CHAR_SIZE
#define com_artifex_gsjava_util_NativePointer_CHAR_SIZE 2i64
#undef com_artifex_gsjava_util_NativePointer_SHORT_SIZE
#define com_artifex_gsjava_util_NativePointer_SHORT_SIZE 2i64
#undef com_artifex_gsjava_util_NativePointer_INT_SIZE
#define com_artifex_gsjava_util_NativePointer_INT_SIZE 4i64
#undef com_artifex_gsjava_util_NativePointer_LONG_SIZE
#define com_artifex_gsjava_util_NativePointer_LONG_SIZE 8i64
/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    mallocNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_gsjava_util_NativePointer_mallocNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    callocNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_gsjava_util_NativePointer_callocNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    freeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_util_NativePointer_freeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    byteArrayNative
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_artifex_gsjava_util_NativePointer_byteArrayNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    byteAtNative
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_com_artifex_gsjava_util_NativePointer_byteAtNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    setByteNative
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_util_NativePointer_setByteNative
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    charArrayNative
 * Signature: (JJ)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_artifex_gsjava_util_NativePointer_charArrayNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    charAtNative
 * Signature: (JJ)C
 */
JNIEXPORT jchar JNICALL Java_com_artifex_gsjava_util_NativePointer_charAtNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    setCharNative
 * Signature: (JJC)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_util_NativePointer_setCharNative
  (JNIEnv *, jclass, jlong, jlong, jchar);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    shortArrayNative
 * Signature: (JJ)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_artifex_gsjava_util_NativePointer_shortArrayNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    shortAtNative
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_com_artifex_gsjava_util_NativePointer_shortAtNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    setShortNative
 * Signature: (JJS)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_util_NativePointer_setShortNative
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    intArrayNative
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_artifex_gsjava_util_NativePointer_intArrayNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    intAtNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_artifex_gsjava_util_NativePointer_intAtNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    setIntNative
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_util_NativePointer_setIntNative
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    longArrayNative
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_artifex_gsjava_util_NativePointer_longArrayNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    longAtNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_artifex_gsjava_util_NativePointer_longAtNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_artifex_gsjava_util_NativePointer
 * Method:    setLongNative
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_artifex_gsjava_util_NativePointer_setLongNative
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
