
// This file has been generated by the GUI designer. Do not modify.
namespace gtk_viewer.src
{
	public partial class gsOutput
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget gtk_viewer.src.gsOutput
			this.Name = "gtk_viewer.src.gsOutput";
			this.Title = global::Mono.Unix.Catalog.GetString("gsOutput");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
